### ISSUE TITLE
composer install error 

### ISSUE THREAD

**Issue by mbouazza** [SocietyCMS/SocietyCMS#1]
Need help in this party  #> composer install 
................ 
`Generating autoload files

> php artisan clear-compiled

  [Illuminate\Database\QueryException]  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_societycms.user__permissions' doesn't exist (SQL: select \* from `user__permissions` where `name` = menu::manage-menu limit 1)  

  [PDOException]  
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_societycms.user__permissions' doesn't exist  

Script php artisan clear-compiled handling the post-install-cmd event returned with an error
`

**Comment by rhwilr** [comment]
The reason you got this error is because i accidentally committed  the composer.lock file with outdated versions of my modules. I removed the .lock file from the repo. 
If you do a `composer create-project societycms/societycms dev-master` you should get the latest version which should work.

After the composer install there will be an error because it tries to acces the database which isn't configured at this point. So sou have to edit the .env and then run these commands manually:

`php artisan clear-compiled`
`php artisan stylist:publish`
`php artisan module:publish`
`php artisan optimize`

**Comment by mbouazza** [comment]
the first time I turned off all the module so that I could make a diagnosis?
Module.json "active": 0,
and I did the migration for each module by specifying the name? for permissions and Roles do not work with the command seed Module ??? I have done manually
in the end it works
my distinguished salutation
![capture d ecran 2016-02-14 a 00 52 46](https://cloud.githubusercontent.com/assets/2506347/13030752/cbce820a-d2b5-11e5-9263-3f92292b436b.png)
